spring.datasource.url=jdbc:postgresql://localhost:5432/papitometro_copa
spring.datasource.username=postgres
spring.datasource.password=mari

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=papitometro-copa-2026-chave-secreta-super-segura-para-jwt
jwt.expiration=86400000

football.api.token=09b75a5fe9634ff4b4205afde55799ad
football.api.url=https://api.football-data.org/v4/competitions/WC/matches